### PR TITLE
Python 3 support

### PR DESCRIPTION
**Pull request by dysosmus**
Support of python 3 by using the `future` package and py2/3 compatible idioms.
This pull request also adds a `tox.ini` to ease multiple versions testing. 
All the tests are passing with the following versions of python: `py26`, `py27`, `py35`,  `pypy` and  `pypy3`.

### CODE REVIEW

**Comment by jelmer** [comment]
Thanks for working on Python3 support!

Fastimport streams are bytestreams, not unicode. I'll see if I can address this myself.
 
I would prefer to avoid an extra dependency (fastimport currently has none). Can we avoid future?

**Comment by jelmer** [comment]
Reading bytestreams rather than unicode streams is nontrivial; can you have a look?

**Comment by dysosmus** [comment]
Indeed, my bad, I will fix it. 
For the future dependency, I think it's possible to avoid it without too much trouble.

**Comment by dysosmus** [comment]
I removed the `future` dependency and updated the code to explicitly use byte strings and not unicode.
For the moment I have dropped the support of `python 3.2/3.3/3.4` because they don't support byte string formatting, so only  `python 3.5` is supported at the moment.

**Comment by jelmer** [comment]
On Mon, Apr 18, 2016 at 09:16:14AM -0700, Félix wrote:
> I removed the `future` dependency and updated the code to explicitly use byte strings and not unicode.
> For the moment I have dropped the support of `python 3.2/3.3/3.4` because they don't support byte string formatting, so only  `python 3.5` is supported at the moment.
That seems reasonable. Thanks again! I'll merge and release a new
version.

Jelmer

**Pull request merged**
